version: '2'

services:
  webapp:
    image: buddyingdevelopment/php:5.6-apache
    container_name: slim-webapp
    working_dir: /var/www/vhosts/slim/htdocs
    depends_on:
      - smtp
    volumes:
      - ../htdocs:/var/www/vhosts/slim/htdocs:cached
      - ./setup/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
    ports:
      - '80:80'
    environment:
      - PHP_XDEBUG=off
      - COMPOSER_ALLOW_SUPERUSER=1

  smtp:
    image: schickling/mailcatcher
    container_name: slim-smtp
    ports:
      - "1080:1080"
      - "1025:1025"